### ISSUE TITLE
Job stuck on queue for 3 hours

### ISSUE THREAD

**Issue by winiciuscota** [frankhommers/Hangfire.PostgreSql#161]
I have hangfire running almost perfectly in production for 2 weeks, this is the second time I have this issue where a recurring job is enqueued on the correct time but is only processed a few hours later(on the first time it was processed 1:30 hour after being enqueued). There was no downtime on the databases nor the servers.

![image](https://user-images.githubusercontent.com/6284656/88822918-dc55ca00-d19a-11ea-8c6a-202637e19688.png)

Is it possible that this is a bug on Hangfire.PostgreSql? Or maybe I'm missing some important configuration?

I'm using Hangfire 1.7.11 and Hangfire.PostgreSql 1.7.0 with 2 instances running 10 workers each

**Comment by andnig** [comment]
Hey, it seems we run into a very similar issue. 

We use Hangfire 1.7.11 and Hangfire.PostgreSql 1.7.1. 
Configuration very similar to winiciuscotas setup

ASP.NET CORE 3.1

Any tips, how we could work around this issue?

Thanks for any input.

**Comment by winiciuscota** [comment]
A few updates

The delay always lasted in multiples of 30 minutes(eg 1:30h, 2:00, 3:00). Maybe Hangfire was attempting to retry after some error? But I didn't find any error logs
Having any task running every hour dramatically reduces the number of occurrences
After switching to the Redis adapter 2 weeks ago there were no more occurrences of this issue

**Comment by ArthurDmytrenko** [comment]
We have faced the same issue any updates on this?

**Comment by jblackwood12** [comment]
I am also experiencing this issue. The delay appears to be some multiple of the configured "InvisibilityTimeout", in your situation it is 30 minutes. In my situation I have it configured to 60 minutes, so sometimes my job will have a latency (or delay) of 1 hour. 

If I had to guess, there is some kind of bug where either:

- Some kind of race condition, and if it is not met, then a delay of the time equivalent to the "InvisibilityTimeout" is added. (more likely)
- Perhaps the TimeSpan configured for the "InvisibilityTimeout" is used in place for the "StartedAt" (less likely)


You can see the attached information from my "state" table, where the "StartedAt" was nearly exactly 60 minutes after the "EnqueuedAt", which is what I have my "InvisibilityTimeout" configured to.

![delayed_job](https://user-images.githubusercontent.com/1121175/109819828-73d43d00-7c02-11eb-92a8-cbb79b0a62a2.png)

**Comment by DanBrk** [comment]
I am facing the same problem.
I am using Hangfire 1.7.18, PostgreSQL Server 1.8.1, .net core with .NET 5 runtime. My application runs on IIS configured to In-Process hosting.

Sometime jobs are running on time but most of the times they are enqueued on time and processing later.

![image](https://user-images.githubusercontent.com/48959452/110244839-53411580-7f69-11eb-9781-54912dda4065.png)

**Comment by rosenbjerg** [comment]
Also facing this issue in production. Would be nice to hear back fra a contributor of this repo ..

**Comment by rosenbjerg** [comment]
@frankhommers Have you had a look at this problem yet?

**Comment by jblackwood12** [comment]
Experienced this issue again, the job was delayed by 2 hours 30 minutes (a multiple of my InvisibilityTimeout of 30 minutes), see the latency in the screenshot (the job took 16 minutes to process). If I had to guess, perhaps it's a race condition each time the job is picked up, the job is potentially hidden from the worker trying to pick up the job for the duration of the InvisibilityTimeout. 

It looks like most of the code that involves the **InvisibilityTimeout** is in the **[PostgreSqlJobQueue.cs](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs)** (potentially between lines 58-213), but I am not familiar enough with this code, so I'll take a few looks at this, but I'm not sure if I'll be able to track down what is causing this issue.

If there are other sections of the code that could cause this issue that someone could point me to, that'd be helpful as well.

![delayed_job_information_3-22-2021](https://user-images.githubusercontent.com/1121175/111992301-9fed2a80-8aeb-11eb-9338-c514665e870f.png)

**Comment by jblackwood12** [comment]
This could be totally off base, but a developer of Hangfire [recommended using](https://discuss.hangfire.io/t/many-workers-execute-my-job/569/6) "wrap these lines in a repeatable read transaction." (IsolationLevel.RepeatableRead) This is with regards to modifying the "FetchedAt" property, to ensure that multiple workers can't modify the "FetchedAt" property at the same time.

But, in the[ PostgreSqlJobQueue.cs on line 97](https://github.com/frankhommers/Hangfire.PostgreSql/blob/140a791513437f4bdf4a21d3bfe36c80d1ae0472/src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs#L97), the "IsolationLevel.ReadCommitted" is used here instead.

The reason I think this may not be a helpful change, is the people having issues are seeing multiple workers process their jobs, where as the issue we're seeing here is that the jobs are just delayed (a certain multiple of our InvisibilityTimeout).

I apologize if this is causing spam for anyone, I just want to see if I can help solve this issue.

**Comment by Frazi1** [comment]
1) Could you guys please post full configuration lines you have in `UsePostgreSqlStorage`? In particular, I'm interested in whether you run with `UseNativeDatabaseTransactions` or not. If it's disabled, try enabling it.

2)How frequently does it happen? How many jobs are enqueued in total when you see that a particular job is delayed?

I've been running in production for about 1 month now, and haven't noticed this kind of issue. However, my use case is probably different. We create tons of jobs on a regular basis (daily, weekly, etc). Some of them are long running and can take up to 5 hours. So in my scenario it is normal that the queue is backed up for hours or even days because I just don't have enough processing power yet. And maybe that's why I couldn't notice the issue.

**Comment by jblackwood12** [comment]
@Frazi1 
1). 
`
// I am using the default for "UseNativeDatabaseTransactions" which appears to be true.
InvisibilityTimeout = TimeSpan.FromMinutes(30), // have jobs that take 6-12 minutes to run.
QueuePollInterval = TimeSpan.FromSeconds(20),
DistributedLockTimeout = TimeSpan.FromMinutes(1) // to avoid the "Hangfire.PostgreSql.PostgreSqlDistributedLockException"
`

2). The job I am running is currently once every morning at about 3:00am EST. No other jobs are run throughout the day currently. The bug where the latency of the job is some multiple of the InvisibilityTimeout appears to happen about 1/4 of the time. For example, the InvisibilityTimeout is set to 30 minutes, and sometimes the latency is 30 minutes, or recently it was 2 hours 30 minutes.

As a side note, I am now trying ```UseNativeDatabaseTransactions = false``` because that appears to default to true. Also, by using ```false``` the code uses two separate SQL queries (see the [PostgreSqlJobQueue.cs](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs) lines 162-178), which appears to be similar to how the [Hangfire.MySql adapter](https://github.com/arnoldasgudas/Hangfire.MySqlStorage/blob/0bd1016f715c8c6617ce22fb7b2ce5b6c328d2fb/Hangfire.MySql/JobQueue/MySqlJobQueue.cs#L46) (see lines 46-70) does it.

**Comment by rosenbjerg** [comment]
@Frazi1 same as jblackwood12 here, we are also using the default for `UseNativeDatabaseTransactions`

**Comment by Frazi1** [comment]
## IIS troubleshooting
@DanBrk mentioned that he runs on IIS with `InProcess` hosting. What about others? Do you also run IIS?

Hangfire is known to have trouble running under IIS due to app pool recycling and other stuff. Maybe that is in some way related. I'm not sure though. I would suggest that you follow the instructions explained here: https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html. Just to make sure.

As I mentioned above, I have been running Hangfire with Postgres for a month without issues. But it runs under Kestrel on Linux, no IIS.

## Invisibility timeout
I can't imagine a scenario when having multiple workers could lead to concurrency issues and result in jobs being delayed. However, if there is an issue caused by the `InvisibilityTimeout` then I would assume that your job has `fetchedat` column set to some value, but no application worker is actually processing that job, and no other worker can see it until the `InvisibilityTimeout` expires. Again, I do not know how it can be possible provided that you run with `UseNativeDatabaseTransactions` enabled.

@frankhommers @vytautask @yongliu-mdsol do you guys have any ideas if that is possible?

We can try to verify it. Though, it can be difficult to track down. So, here is my suggestion:
1) Try to manually monitor the dashboard when your recurring job is about to be scheduled and started
2) If you see the delay, run the following sql query against your hangfire database:
    ```sql
    select * from hangfire.jobqueue
    where jobid = <job_id>
    ```
3) Pay attention to `fetchedat` column
    * if it is `null`, then the job should be visible to workers.
    * if it is **not** `null` and the job is not being processed, then we have a bug in the fetching logic.

Anyway, I'll try to reproduce that issue locally. I have set up a hangfire process that runs 2 recurring jobs: daily and hourly.

**Comment by rosenbjerg** [comment]
@Frazi1 We run without IIS, using Kestrel instead. The application is running inside a Linux container

**Comment by jblackwood12** [comment]
@Frazi1 I am using Kestrel as well, running on a Linux machine.

**Comment by vytautask** [comment]
The way I see it - debugging this is hard. Ensuring that this is fixed is hard as well.
To make this easier we need a unit-test (or, to be precise, integration test). Then we could make sure it works after the implemented fix.
Without a proper test, it would be just a fine example of "cowboy coding"...

**Comment by ahjashish** [comment]
Even I am facing the same problem. Earlier I ignored it as an anomaly but now it's starting to occur again and again. I am running with .NET 3.1 core on a docker container in K8s cluster.
Here are the packages I am using :
`<PackageReference Include="Hangfire" Version="1.7.19" />
      <PackageReference Include="Hangfire.AspNetCore" Version="1.7.19" />
      <PackageReference Include="Hangfire.Core" Version="1.7.19" />
      <PackageReference Include="Hangfire.MemoryStorage" Version="1.7.0" />
      <PackageReference Include="Hangfire.PostgreSql" Version="1.8.2" />`

**Comment by OVSQualityBCH** [comment]
We experience the same issue using Kestrel on a Linux machine using Docker containers using versions 1.8.2 with Hangfire 1.7.20.

**Comment by runedegroot** [comment]
We experience the same issue using Kestrel on a Linux machine using Docker containers using versions 1.8.2 with Hangfire 1.7.20.

**Comment by Frazi1** [comment]
@jblackwood12
Any success running with `UseNativeDatabaseTransactions=false`?

**Comment by jblackwood12** [comment]
> @jblackwood12
> Any success running with `UseNativeDatabaseTransactions=false`?

We've had some network issues that have prevented us from running this job over the last week, so, unfortunately I don't have date to share yet. Probably will have information within a week or so. 

As far as I can tell, there should be no risk to using `UseNativeDatabaseTransactions=false`, all it does it separate one SQL query into two. It does it similar to how the MySQL adapter for Hangfire does it by default.

**Comment by Plasma** [comment]
I’m looking to use Hangfire with Pg, stumbled across this issue.

I tried reproducing locally but had no luck.

It’s quite confusing, but wanted to offer some ideas in case it helps track down what’s going on:

1. I note the usage of Now() uses the transaction start time, so if there are outer transactions that have been open for a while perhaps this is causing this value to be unexpectedly old?
2. The invisibility timeout multiplier is interesting, I note the code swallows a certain exception code on job fetch, but if that was triggered then I don’t see the job state being updated
3. Could there be some issue where the job data is not inserted ahead of the recurring job row so when it’s fetched at is updated, it eventually can’t load the job (seems doubtful)
4. The “get next job” code prefers a job with a null fetchedat as opposed to an old value
5. The screenshots don’t show any other state transitions for the job, I tried to see if “skip locked” could ever keep skipping a row due to other reasons (eg table had its locks promoted to page or table locks due to table size) causing that row to be hidden more often than expected, but that seems unlikely
6. The invisibility timeout multiplier makes me feel like the job has its fetchedat updated, but then failed to eventually have its job data resolved from the other table and processed. Maybe a problem with PostgresWriteOnlyTransaction logic when it creates a recurring job?
7. Not sure if this is pg Linux specific 
8. Not sure if it’s timing related (local app vs pg server time)

**Comment by Plasma** [comment]
Also, noticed https://github.com/npgsql/npgsql/issues/2408 was fixed yesterday, non-pooled connections not being enlisted in transactions. By chance are people here turning off connection pooling?

**Comment by stormoz** [comment]
We actually DO have the pooling off.
The reason is that we fully rely on PgBouncer to handle pooling.

**Comment by DanBrk** [comment]
> I am facing the same problem.
> I am using Hangfire 1.7.18, PostgreSQL Server 1.8.1, .net core with .NET 5 runtime. My application runs on IIS configured to In-Process hosting.
> 
> Sometime jobs are running on time but most of the times they are enqueued on time and processing later.
> 
> ![image](https://user-images.githubusercontent.com/48959452/110244839-53411580-7f69-11eb-9781-54912dda4065.png)



> I am facing the same problem.
> I am using Hangfire 1.7.18, PostgreSQL Server 1.8.1, .net core with .NET 5 runtime. My application runs on IIS configured to In-Process hosting.
> 
> Sometime jobs are running on time but most of the times they are enqueued on time and processing later.
> 
> ![image](https://user-images.githubusercontent.com/48959452/110244839-53411580-7f69-11eb-9781-54912dda4065.png)

I want to add that during the latency time every 30 minutes I receive the following error:
10 state change attempt(s) failed due to an exception, moving job to the FailedState
```
Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:job:116:state-lock': Lock timeout.
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlDistributedLock..ctor(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(IStorageConnection connection, String jobId, TimeSpan timeout)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
```

**Comment by DanBrk** [comment]
I noticed that the logs include some PostgreSqlDistributedLockException that occurs every 30 minutes after the job has been enqueued:
```
10 state change attempt(s) failed due to an exception, moving job to the FailedState
Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:job:116:state-lock': Lock timeout.
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlDistributedLock..ctor(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(IStorageConnection connection, String jobId, TimeSpan timeout)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
```
What can solve that ?

**Comment by nevaldas** [comment]
We are running on linux and docker containers as well. And we found a solution for this. We even created [a pull request](https://github.com/frankhommers/Hangfire.PostgreSql/pull/188 ), which is still open. 

Summary - if for some reason a connection was dropped by your infrastructure (and in our case, the docker is very unstable), this library then tries to place a lock with already closed connection. It never reopens it. And this network related issue is hidden by swallowing the exception when trying to remove a deadlock ([TryRemoveDeadlock method in PostgreSqlDistributedLock.cs](https://github.com/frankhommers/Hangfire.PostgreSql/blob/1.8.3/src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs#L130)). 
The connection itself is opened at [CreateAndOpenConnection in PostgreSqlStorage.cs](https://github.com/frankhommers/Hangfire.PostgreSql/blob/1.8.3/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L197), which is called [when trying to fetch a job](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/Worker.cs#L99).

**Comment by vytautask** [comment]
Could be that the issue is solved with @azygis - provided PR with version 1.8.4.
Please confirm.

**Comment by OVSQualityBCH** [comment]
I can confirm I get the same exception as @DanBrk mentioned. The problem has not occurred yet with version 1.8.4.

**Comment by runedegroot** [comment]
I can confirm I get the same exception as @DanBrk mentioned. The problem has not occurred yet with version 1.8.4.

**Comment by runedegroot** [comment]
I still get the following warnings:
```
HangFire:job:93:state-lock: Failed to remove lock,
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream,
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.,
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer,
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size),
   --- End of inner exception stack trace ---,
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size),
   at Npgsql.NpgsqlReadBuffer.<Ensure>g__EnsureLong|40_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications),
   at Npgsql.NpgsqlReadBuffer.<Ensure>g__EnsureLong|40_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications),
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage),
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage),
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken),
   at Npgsql.NpgsqlDataReader.NextResult(),
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken),
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken),
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken),
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(),
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822,
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572,
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443,
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.TryRemoveDeadlock(String resource, IDbConnection connection, PostgreSqlStorageOptions options),
HangFire:job:93:state-lock: Failed to lock with transaction,
System.InvalidOperationException: Connection is not open,
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level, Boolean async, CancellationToken cancellationToken),
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level),
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options),
```

**Comment by azygis** [comment]
As @vytautask said in my PR - the fix was really just a band-aid so the retry at least works. We do still get exception from time to time in the logs, but since first retry happens after a second or so and then it succeeds, we were pleased with the results, since in the end the job does it's job (no pun intended). If you potentially also have issues with your infrastructure similar to us, when the connection gets dropped (in your case it's connection reset, in our case it was "attempted to read past the end of stream") abruptly, just ignore the exception, as long as the job gets processed. If the issue persists even when retrying - you should really check what's happening with your database or network.

**Comment by Plasma** [comment]
These broken connection issues I’ve seen in other infrastructure when using cloud services. The root cause is that the networking layer likes to (sometimes quietly) close/reset what it feels are idle connections after a few minutes.

A potential workaround could be to also alter the connection string to prune idle connections automatically after (say) 1 minute, so there’s little to no chance connections returned from the pool are broken.

See https://www.npgsql.org/doc/connection-string-parameters.html#timeouts-and-keepalive

**Comment by DanBrk** [comment]
1.8.4 release solved the issue for me. Thanks
